# Generated by Django 5.2.7 on 2025-11-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the client making the request')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time when request was made')),
                ('path', models.CharField(help_text='URL path for the request', max_length=2048)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='ip_tracking_timesta_6f54b9_idx'), models.Index(fields=['ip_address'], name='ip_tracking_ip_addr_3489f7_idx')],
            },
        ),
    ]
