# Generated by Django 5.2.7 on 2025-11-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address to block', unique=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for blocking this IP address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this IP was blocked')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this block is currently active')),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'is_active'], name='ip_tracking_ip_addr_baa190_idx')],
            },
        ),
    ]
