# Generated by Django 5.2.7 on 2025-11-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0003_requestlog_city_requestlog_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Suspicious IP address')),
                ('reason', models.TextField(help_text='Reason why this IP was flagged as suspicious')),
                ('flagged_at', models.DateTimeField(auto_now_add=True, help_text='When this IP was flagged')),
                ('request_count', models.IntegerField(default=0, help_text='Number of requests in the detection period')),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether this flag has been reviewed and resolved')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When this flag was resolved', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this flag', null=True)),
            ],
            options={
                'verbose_name': 'Suspicious IP',
                'verbose_name_plural': 'Suspicious IPs',
                'ordering': ['-flagged_at'],
                'indexes': [models.Index(fields=['ip_address'], name='ip_tracking_ip_addr_11f206_idx'), models.Index(fields=['is_resolved'], name='ip_tracking_is_reso_ccfb1f_idx'), models.Index(fields=['-flagged_at'], name='ip_tracking_flagged_dede4e_idx')],
            },
        ),
    ]
